name: linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Setup Paket
      run: dotnet tool restore
    - name: Install dependencies
      run: dotnet paket restore
    - name: Build (Debug)
      run: dotnet build src/Aardvark.Data.Durable.sln --configuration Debug
    - name: Build (Release)
      run: dotnet build src/Aardvark.Data.Durable.sln --configuration Release
    - name: Test (Debug)
      run: dotnet test src/Aardvark.Data.Durable.sln --verbosity normal --configuration Debug
    - name: Test (Release)
      run: dotnet test src/Aardvark.Data.Durable.sln --verbosity normal --configuration Release
